name = "rift-survival-core"
main = "src/realtime-entry.js"
compatibility_date = "2026-08-01"

assets = { directory = "./public", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "rift-survival-v2"
database_id = "118e392b-e9d4-4d81-9a4f-ee2a2b3865cc"

[[durable_objects.bindings]]
name = "PLAYER_STATE"
class_name = "PlayerState"

[[durable_objects.bindings]]
name = "ZONE_STATE"
class_name = "ZoneState"

[[migrations]]
tag = "player-state-v1"
new_sqlite_classes = ["PlayerState"]

[[migrations]]
tag = "zone-state-v1"
new_sqlite_classes = ["ZoneState"]
